import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const baseURL = process.argv[2] || process.env.APP_URL || 'http://127.0.0.1:5173';
const dir = 'artifacts/browser'; await mkdir(dir, {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:2});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto(baseURL + '/');
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:`${dir}/desktop-intro.png`,animations:'disabled',fullPage:true});
await page.getByRole('button',{name:'광고 진단 시작하기'}).click();
await page.getByRole('radio',{name:'음식점/카페',exact:true}).check();
assert.equal(await page.getByRole('radio',{checked:true}).count(),1);
await page.screenshot({path:`${dir}/desktop-question.png`,animations:'disabled',fullPage:true});
await page.getByRole('button',{name:'다음',exact:true}).click();
await page.getByRole('radio',{name:'홈페이지 또는 자사몰에서 구매'}).check();
await page.reload();
await page.getByRole('radio',{name:'홈페이지 또는 자사몰에서 구매'}).waitFor();
assert.equal(await page.getByRole('radio',{name:'홈페이지 또는 자사몰에서 구매'}).isChecked(),true);
await page.goBack();
await page.getByRole('heading',{name:'어떤 업종을 운영하고 계신가요?'}).waitFor();
await page.goForward();
await page.getByRole('button',{name:'다음',exact:true}).click();
await page.getByRole('radio',{name:'전환 부족'}).check();
await page.getByRole('button',{name:'다음',exact:true}).click();
await page.getByRole('radio',{name:'브랜드 인지도 높이기'}).check();
await page.getByRole('button',{name:'결과 보기',exact:true}).click();
await page.locator('.result').waitFor();await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:`${dir}/desktop-result.png`,animations:'disabled',fullPage:true});
const buttons=await page.locator('.actions button').evaluateAll(nodes=>nodes.map(n=>({width:n.getBoundingClientRect().width,top:n.getBoundingClientRect().top})));
assert.ok(buttons.every(b=>Math.abs(b.width-buttons[0].width)<1&&b.top===buttons[0].top));
await page.getByRole('button',{name:'결과 저장하기'}).click();
for(const [format,name] of [['png','이미지로 저장'],['pdf','PDF로 저장']]){
 const pending=page.waitForEvent('download',{timeout:90000});
 await page.getByRole('button',{name,exact:true}).click();
 const download=await pending;await download.saveAs(`${dir}/result.${format}`);
 await page.getByRole('button',{name,exact:true}).waitFor({state:'visible'});
}
await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.getByRole('button',{name:'광고 가이드 받아보기'}).click();
assert.equal(await page.getByRole('button',{name:/메뉴얼/}).isDisabled(),true);
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'다시 진단하기'}).click();
await page.getByRole('button',{name:'광고 진단 시작하기'}).waitFor();
await page.getByRole('button',{name:'광고 진단 시작하기'}).click();
assert.equal(await page.getByRole('radio',{checked:true}).count(),0);
const mobile = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto(baseURL + '/#/result');
await mobile.getByRole('heading',{name:'어떤 업종을 운영하고 계신가요?'}).waitFor();
assert.equal(await mobile.getByRole('button',{name:'다음',exact:true}).isDisabled(),true);
await mobile.locator('.option').last().scrollIntoViewIfNeeded();
await mobile.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));
const lastOption = await mobile.locator('.option').last().boundingBox();
const dock = await mobile.locator('.dock').boundingBox();
assert.ok(lastOption.y + lastOption.height <= dock.y + 1, 'Last choice must be above the fixed button after scrolling');
await mobile.screenshot({path:`${dir}/mobile-question-bottom.png`,animations:'disabled'});
await mobile.evaluate(()=>window.scrollTo(0,0));
await mobile.screenshot({path:`${dir}/mobile-question.png`,animations:'disabled',fullPage:true});
for(const [step,name] of [[0,'부동산/생활 서비스'],[1,'상담 후 구매/계약'],[2,'측정 부족'],[3,'고객 관계 강화']]){
 await mobile.getByRole('radio',{name}).check();
 await mobile.getByRole('button',{name:step===3?'결과 보기':'다음',exact:true}).click();
}
await mobile.locator('.result').waitFor();
assert.equal(await mobile.locator('.advice-context').count(),2);
assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await mobile.screenshot({path:`${dir}/mobile-result.png`,animations:'disabled',fullPage:true});
await mobile.getByRole('button',{name:'결과 저장하기'}).click();
const mobileDownload=mobile.waitForEvent('download',{timeout:90000});await mobile.getByRole('button',{name:'이미지로 저장',exact:true}).click();await (await mobileDownload).saveAs(`${dir}/mobile-result.png-export.png`);
await mobile.getByRole('button',{name:'닫기',exact:true}).click();
await mobile.setViewportSize({width:320,height:700});
assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);
await writeFile(`${dir}/report.json`,JSON.stringify({passed:true,errors,buttonLayout:buttons},null,2));
await browser.close();console.log('Browser verification passed: navigation, session recovery, desktop/mobile layout, PNG/PDF downloads, reset, guide modal.');
